apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qitanoid.fullname" . }}-browser-bootstrap
  labels:
    {{- include "qitanoid.labels" . | nindent 4 }}
data:
  browsers.json: |
{{- if .Values.config.rawJson }}
{{ .Values.config.rawJson | nindent 4 }}
{{- else if .Values.config.file }}
{{ .Files.Get (printf "files/%s" .Values.config.file) | nindent 4 }}
{{- else }}
{{ .Files.Get "files/browsers.json" | nindent 4 }}
{{- end }}
