{{- if and (eq .Values.video.storage.type "s3") (not .Values.video.storage.s3.existingSecret) .Values.video.storage.s3.accessKey .Values.video.storage.s3.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qitanoid.videoS3SecretName" . }}
  labels:
    {{- include "qitanoid.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.video.storage.s3.accessKey | quote }}
  secretKey: {{ .Values.video.storage.s3.secretKey | quote }}
{{- end }}
