{{- if .Values.hub.adminToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qitanoid.fullname" . }}-admin
  labels:
    {{- include "qitanoid.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.hub.adminToken | quote }}
{{- end }}
