{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qitanoid.serviceAccountName" . }}
  labels:
    {{- include "qitanoid.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.session.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qitanoid.sessionServiceAccountName" . }}
  labels:
    {{- include "qitanoid.labels" . | nindent 4 }}
{{- end }}
